export const PROVINCES = [
  "Western",
  "Central",
  "Southern",
  "Northern",
  "Eastern",
  "North Western",
  "North Central",
  "Uva",
  "Sabaragamuwa"
] as const;

export const PROVINCE_DISTRICTS: Record<string, string[]> = {
  "Western": ["Colombo", "Gampaha", "Kalutara"],
  "Central": ["Kandy", "Matale", "Nuwara Eliya"],
  "Southern": ["Galle", "Matara", "Hambantota"],
  "Northern": ["Jaffna", "Kilinochchi", "Mullaitivu", "Mannar", "Vavuniya"],
  "Eastern": ["Trincomalee", "Batticaloa", "Ampara"],
  "North Western": ["Kurunegala", "Puttalam"],
  "North Central": ["Anuradhapura", "Polonnaruwa"],
  "Uva": ["Badulla", "Monaragala"],
  "Sabaragamuwa": ["Ratnapura", "Kegalle"]
};

export const DISTRICTS = Object.values(PROVINCE_DISTRICTS).flat() as readonly string[];


export const SUBJECTS = [
  "101 - Chemistry",
  "102 - Physics",
  "103 - Biology",
  "104 - Agricultural Science",
  "105 - Combined Mathematics",
  "106 - Engineering Technology",
  "107 - Bio Systems Technology",
  "108 - Science for Technology",
  "109 - Information & Communication Technology",
  "110 - Accounting",
  "111 - Business Studies",
  "112 - Business Statistics",
  "113 - Logic and Scientific Method",
  "114 - Economics",
  "115 - Geography",
  "116 - Political Science",
  "117 - Home Economics",
  "118 - History",
  "119 - Communication & Media Studies",
  "120 - Buddhist Civilization",
  "121 - Christian Civilization",
  "122 - Hindu Civilization",
  "123 - Islamic Civilization",
  "124 - Buddhism",
  "125 - Hinduism",
  "126 - Christianity",
  "127 - Islam",
  "128 - Art",
  "129 - Dancing (Traditional)",
  "130 - Dancing (Bharatha)",
  "131 - Oriental Music",
  "132 - Carnatic Music",
  "133 - Western Music",
  "134 - Drama & Theatre",
  "135 - Sinhala",
  "136 - Tamil",
  "137 - English",
  "138 - Arabic",
  "139 - French",
  "140 - Chinese",
  "141 - Japanese",
  "142 - German",
  "143 - Russian",
  "144 - Malay",
  "145 - Hindi",
  "146 - Korean",
  "201 - Child Psychology and Care",
  "202 - Health and Social Care",
  "203 - Physical Education and Sport",
  "204 - Performing Arts",
  "205 - Event Management",
  "206 - Arts and Crafts",
  "207 - Interior Designing",
  "208 - Fashion Designing",
  "209 - Graphic Designing",
  "210 - Landscaping",
  "211 - Applied Horticultural Studies",
  "212 - Livestock Product Studies",
  "213 - Food Processing Studies",
  "214 - Aquatic Resource Studies",
  "215 - Plantation Product Studies",
  "216 - Construction Studies",
  "217 - Automobile Studies",
  "218 - Electrical and Electronic Studies",
  "219 - Textile and Apparel Studies",
  "220 - Metal Fabrication Studies",
  "221 - Aluminum Fabrication Studies",
  "222 - Computer Hardware and Networking",
  "223 - Manufacturing",
  "224 - Tourism & Hospitality",
  "225 - Logistic Management",
  "226 - Marketing",
  "301 - Counselling",
  "302 - Special Education",
  "401 - Science",
  "402 - Mathematics",
  "403 - Sinhala Language & Literature",
  "404 - Tamil Language & Literature",
  "405 - English",
  "406 - History",
  "407 - Geography",
  "408 - Civic Education",
  "409 - Business & Accounting Studies",
  "410 - Entrepreneurship Studies",
  "411 - French",
  "412 - Hindi",
  "413 - Japanese",
  "414 - Arabic",
  "415 - German",
  "416 - Chinese",
  "417 - Russian",
  "418 - Korean",
  "419 - 2nd Language Sinhala",
  "420 - 2nd Language Tamil",
  "421 - Music (Oriental)",
  "422 - Music (Western)",
  "423 - Music (Carnatic)",
  "424 - Art",
  "425 - Dancing (Oriental)",
  "426 - Dancing (Bharatha)",
  "427 - Drama and Theatre",
  "428 - Appreciation of Literary (Sinhala)",
  "429 - Appreciation of Literary (Tamil)",
  "430 - Appreciation of Literary (English)",
  "431 - Appreciation of Literary (Arabic)",
  "432 - Information & Communication Technology",
  "433 - Agriculture & Food Technology",
  "434 - Aquatic Bio Resources Technology",
  "435 - Art and Craft",
  "436 - Home Economics",
  "437 - Practical and Technical Skills",
  "438 - Design and Technology",
  "439 - Health and Physical Education",
  "440 - Communication and Media Studies"
] as const;
